In [1]:
import numpy as np
import pandas as pd

In [2]:
#Create A Datafream
df_metadata= pd.read_csv('/home/becode/BeCode Projects/Mole-Detection-Project/archive/HAM10000_metadata.csv', sep=',')
df_metadata.head(10)

     lesion_id      image_id   dx dx_type   age     sex localization
0  HAM_0000118  ISIC_0027419  bkl   histo  80.0    male        scalp
1  HAM_0000118  ISIC_0025030  bkl   histo  80.0    male        scalp
2  HAM_0002730  ISIC_0026769  bkl   histo  80.0    male        scalp
3  HAM_0002730  ISIC_0025661  bkl   histo  80.0    male        scalp
4  HAM_0001466  ISIC_0031633  bkl   histo  75.0    male          ear
5  HAM_0001466  ISIC_0027850  bkl   histo  75.0    male          ear
6  HAM_0002761  ISIC_0029176  bkl   histo  60.0    male         face
7  HAM_0002761  ISIC_0029068  bkl   histo  60.0    male         face
8  HAM_0005132  ISIC_0025837  bkl   histo  70.0  female         back
9  HAM_0005132  ISIC_0025209  bkl   histo  70.0  female         back

In [3]:
#Checking rows/Avelable rows & columns
df_metadata.shape

(10015, 7)

In [4]:
# Check Duplicates
df_metadata.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
10010    False
10011    False
10012    False
10013    False
10014    False
Length: 10015, dtype: bool

In [5]:
#Count all NaN in a DataFrame (both columns & Rows)
df_metadata.isnull().sum().sum()

57

In [6]:
# Drop all NaN
df_metadata=df_metadata.dropna()

In [7]:
# Chack again metadata file
df_metadata.shape

(9958, 7)

In [8]:
df_8_8_L= pd.read_csv('/home/becode/BeCode Projects/Mole-Detection-Project/archive/hmnist_8_8_L.csv', sep=',')
df_8_8_L.head(10)

,pixel0000,pixel0001,pixel0002,pixel0003,pixel0004,pixel0005,pixel0006,pixel0007,pixel0008,pixel0009,...,pixel0055,pixel0056,pixel0057,pixel0058,pixel0059,pixel0060,pixel0061,pixel0062,pixel0063,label
0,172,182,191,183,180,181,165,164,173,192,...,159,171,181,201,192,184,183,171,157,2
1,98,149,170,193,183,162,164,100,137,175,...,135,83,159,186,185,192,181,143,58,2
2,165,164,179,172,152,163,169,151,168,174,...,169,152,171,185,189,193,176,168,151,2
3,109,159,167,166,163,159,155,96,141,168,...,101,79,146,170,167,158,154,133,45,2
4,173,202,210,194,208,248,243,205,180,142,...,230,160,199,206,208,209,205,200,186,2
5,17,155,229,233,234,205,134,43,69,180,...,31,33,112,178,149,122,171,80,0,2
6,168,170,169,178,177,174,168,161,176,179,...,178,174,185,184,188,188,183,180,177,2
7,141,153,162,171,174,171,152,119,152,168,...,145,144,164,180,179,180,173,164,107,2
8,138,157,177,182,181,174,159,143,153,178,...,146,97,150,161,162,168,160,153,92,2
9,181,173,191,197,198,181,187,196,181,188,...,185,170,176,187,196,204,198,186,168,2

In [9]:
df_8_8_RGB= pd.read_csv('/home/becode/BeCode Projects/Mole-Detection-Project/archive/hmnist_8_8_RGB.csv', sep=',')
df_28_28_L= pd.read_csv('/home/becode/BeCode Projects/Mole-Detection-Project/archive/hmnist_28_28_L.csv', sep=',')
df_28_28_RGB= pd.read_csv('/home/becode/BeCode Projects/Mole-Detection-Project/archive/hmnist_28_28_RGB.csv', sep=',')